#!/usr/bin/env python

import os, sys
import subprocess
import glob

here = os.path.dirname(__file__)
whitespace_lint_path = os.path.normpath(os.path.join(here, "..", "whitespace_lint"))

def main():
  returncode = 0
  test_inputs = sorted(glob.glob(os.path.join(here, "*.in")))
  for test_input in test_inputs:
    actual_output = subprocess.check_output([whitespace_lint_path, test_input])
    expected_output = read_file(test_input.replace(".in", ".out"))
    if actual_output != expected_output:
      sys.stderr.write("FAIL: %s: expected: %s, got: %s\n" % (os.path.basename(test_input), repr(expected_output), repr(actual_output)))
      returncode = 1
  sys.exit(returncode)

def read_file(path):
  with open(path) as f:
    return f.read()

if __name__ == "__main__":
  main()
